# Generated by Django 5.0.1 on 2024-01-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gundepot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.FloatField()),
                ('pdetails', models.CharField(max_length=40, verbose_name='product details')),
                ('category', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='available')),
            ],
        ),
    ]
