# Generated by Django 5.0.1 on 2024-01-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gundepot', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='piamge',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
